### ISSUE TITLE
Unneccesary check if can write in the error log file

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-errorhandler#1]
Every time the script is run, is checking if can write in the log file

Probably is a good idea to be called only when is the case ?

**Comment by arhimede** [comment]
BUMP

**Comment by bidi47** [comment]
i can't find that code.
what is the file is should be checking?

**Comment by arhimede** [comment]
see this line 
https://github.com/laminas/laminas-log/blob/2.18.x/src/Writer/Stream.php#L105C13-L105C63

**Comment by arhimede** [comment]
It seem that at each request, the log file is fopened, so yeah,
