### ISSUE TITLE
Bump to PHP 8.3

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-errorhandler#27]

**Comment by bidi47** [comment]
update blocked by
dotkernel/dot-log (@Jurj-Bogdan ) - please release with version 3.4.4

**Comment by Jurj-Bogdan** [comment]
Updating dotkernel/dot-log is currently blocked by laminas/laminas-log

**Comment by arhimede** [comment]
https://github.com/laminas/laminas-log/releases/tag/2.17.0

**Comment by arhimede** [comment]
fixed in #28
